// ============================================================================
// /api/fakeit-video.js  —  "Fake It: Video" — a video of YOU, anywhere.
// ----------------------------------------------------------------------------
// HOW IT WORKS (and why it's built this way):
//   Google Flow has an "Avatar" feature — record a selfie, star in any video.
//   That is Flow-only; there is NO avatar endpoint in the Gemini API.
//
//   What the API DOES give us is better than a workaround: Veo 3.1 accepts up
//   to 3 REFERENCE IMAGES of a person ("referenceType": "asset") and preserves
//   that person's appearance in the video. So we feed it images generated by
//   the user's own trained Fake It model — and the video is really them.
//
//   Google recommends exactly this chain: generate stills, pass them to Veo.
//
// FALLBACK: reference images are a preview feature and have been flaky in some
// regions. If Veo rejects them, we retry as plain image-to-video using the
// first image as the opening frame — still the user's face, just less control.
//
// Env: GEMINI_API_KEY, SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY
// ============================================================================

const SB_URL  = (process.env.SUPABASE_URL || "").trim();
const SB_ANON = (process.env.SUPABASE_ANON_KEY || "").trim();
const SB_SVC  = (process.env.SUPABASE_SERVICE_ROLE_KEY || "").trim();

// Per-second credit cost, matching the UGC Studio tiers.
const TIERS = {
  veolite: { model: "veo-3.1-lite-generate-preview", res: "720p",  per: 150  },
  veofast: { model: "veo-3.1-fast-generate-preview", res: "720p",  per: 300  },
  veo:     { model: "veo-3.1-generate-preview",      res: "1080p", per: 1250 },
};

const BLOCKED = [
  "nude","naked","nsfw","porn","explicit","topless","sexual","erotic","fetish",
  "child","kid","minor","teen","underage",
];

async function getUserId(token) {
  if (!token) return null;
  try {
    const r = await fetch(SB_URL + "/auth/v1/user", {
      headers: { apikey: SB_ANON, Authorization: "Bearer " + token },
    });
    const u = await r.json();
    return r.ok && u && u.id ? u.id : null;
  } catch { return null; }
}
async function spend(token, amount, reason) {
  try {
    const r = await fetch(SB_URL + "/rest/v1/rpc/spend_credits", {
      method: "POST",
      headers: { apikey: SB_ANON, Authorization: "Bearer " + token, "Content-Type": "application/json" },
      body: JSON.stringify({ p_amount: amount, p_reason: reason }),
    });
    const d = await r.json();
    if (!r.ok) return { ok: false, error: (d && d.message) || "Could not deduct credits." };
    return { ok: true, balance: typeof d === "number" ? d : null };
  } catch { return { ok: false, error: "Credit service unreachable." }; }
}
async function refund(userId, amount, reason) {
  try {
    await fetch(SB_URL + "/rest/v1/rpc/add_credits", {
      method: "POST",
      headers: { apikey: SB_SVC, Authorization: "Bearer " + SB_SVC, "Content-Type": "application/json" },
      body: JSON.stringify({ p_user: userId, p_amount: amount, p_reason: reason }),
    });
  } catch {}
}
async function recordVideoJob(id, userId, cost) {
  try {
    await fetch(SB_URL + "/rest/v1/video_jobs", {
      method: "POST",
      headers: { apikey: SB_SVC, Authorization: "Bearer " + SB_SVC, "Content-Type": "application/json", Prefer: "return=minimal" },
      body: JSON.stringify({ id: String(id), user_id: userId, cost }),
    });
  } catch {}
}

// Turn a data-url or http url into { bytesBase64Encoded, mimeType } for Google.
async function toInline(img) {
  if (!img) return null;
  if (/^data:.*;base64,/.test(img)) {
    const m = img.match(/^data:(.*?);base64,(.*)$/);
    return { bytesBase64Encoded: (m && m[2]) || "", mimeType: (m && m[1]) || "image/jpeg" };
  }
  if (/^https?:\/\//.test(img)) {
    const r = await fetch(img);
    if (!r.ok) return null;
    const buf = Buffer.from(await r.arrayBuffer());
    return { bytesBase64Encoded: buf.toString("base64"), mimeType: r.headers.get("content-type") || "image/jpeg" };
  }
  return null;
}

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const GKEY = (process.env.GEMINI_API_KEY || "").trim();
  if (!GKEY || !SB_URL) return res.status(500).json({ error: "Video is not configured." });

  const token = (req.headers.authorization || "").replace(/^Bearer\s+/i, "").trim();
  const userId = await getUserId(token);
  if (!userId) return res.status(401).json({ error: "Please log in again." });

  const body = typeof req.body === "string" ? JSON.parse(req.body || "{}") : (req.body || {});
  const images = Array.isArray(body.images) ? body.images.slice(0, 3) : [];
  const prompt = (body.prompt || "").trim();
  const say = (body.say || "").trim();
  const tierId = TIERS[body.tier] ? body.tier : "veolite";
  const tier = TIERS[tierId];
  const orientation = body.orientation === "landscape" ? "landscape" : "portrait";
  const duration = [4, 6, 8].includes(Number(body.duration)) ? Number(body.duration) : 8;

  if (!images.length) return res.status(400).json({ error: "Pick at least one Fake It photo of yourself." });
  if (prompt.length < 3) return res.status(400).json({ error: "Describe what's happening in the video." });

  const low = (prompt + " " + say).toLowerCase();
  if (BLOCKED.some((w) => low.includes(w))) {
    return res.status(400).json({ error: "That's outside what Fake It is for. Try a place, an outfit, or an action." });
  }

  const cost = tier.per * duration;

  // Build the full prompt. Speech in the prompt gives Veo synchronized lip-sync.
  let fullPrompt = prompt;
  if (say) fullPrompt += '\nThe person says: "' + say + '"';

  const aspectRatio = orientation === "portrait" ? "9:16" : "16:9";

  try {
    const inline = [];
    for (const img of images) {
      const i = await toInline(img);
      if (i) inline.push(i);
    }
    if (!inline.length) return res.status(400).json({ error: "Couldn't read those photos. Try again." });

    const paid = await spend(token, cost, "fakeit-video:" + tierId + ":" + duration + "s");
    if (!paid.ok) return res.status(402).json({ error: paid.error });

    const url =
      "https://generativelanguage.googleapis.com/v1beta/models/" + tier.model + ":predictLongRunning";
    const params = {
      aspectRatio,
      resolution: tier.res,
      durationSeconds: duration,
      generateAudio: true,
      sampleCount: 1,
      personGeneration: "allow_adult",
    };

    // --- Attempt 1: reference images (keeps THEIR face across the whole clip)
    let r = await fetch(url, {
      method: "POST",
      headers: { "x-goog-api-key": GKEY, "Content-Type": "application/json" },
      body: JSON.stringify({
        instances: [{
          prompt: fullPrompt,
          referenceImages: inline.map((i) => ({ image: i, referenceType: "asset" })),
        }],
        parameters: params,
      }),
    });
    let data = await r.json();
    let usedFallback = false;

    // --- Attempt 2 (fallback): plain image-to-video from the first photo.
    // Reference images are a preview feature and can be unavailable by region.
    if (!r.ok) {
      usedFallback = true;
      r = await fetch(url, {
        method: "POST",
        headers: { "x-goog-api-key": GKEY, "Content-Type": "application/json" },
        body: JSON.stringify({
          instances: [{ prompt: fullPrompt, image: inline[0] }],
          parameters: params,
        }),
      });
      data = await r.json();
    }

    if (!r.ok) {
      await refund(userId, cost, "refund:fakeit-video");
      const msg = (data && data.error && data.error.message) || "Video service error";
      return res.status(r.status).json({ error: msg + " Your credits were refunded." });
    }

    const opName = data && data.name;
    if (!opName) {
      await refund(userId, cost, "refund:fakeit-video-noid");
      return res.status(502).json({ error: "No job id returned. Your credits were refunded." });
    }

    const id = "g:" + opName;   // "g:" tells /api/video-result to poll Google
    await recordVideoJob(id, userId, cost);
    return res.status(200).json({ ok: true, id, balance: paid.balance, usedFallback });
  } catch (e) {
    return res.status(500).json({ error: "Could not start that video." });
  }
}
